Feature 1
Sick-Carlito/Apple-Page pull request #1
Opened 2019-08-26 23:27 UTC by Sick-Carlito

2019-08-27 20:50 UTC, Oghenebrume50 requested changes
Hi @Sick-Carlito great start to this project, you are doing amazing :smiley: 
However, this is the current displace of the bottom part, it needs some fixing :wink: 
![11](https://user-images.githubusercontent.com/37092867/63806690-07dd8e00-c914-11e9-9f72-7be18440ad32.png)
Please can you use more semantic HTML like <nav> for navbar and <footer> for the footer. Do these things and submit for a re-review :+1:

2019-08-27 20:50 UTC, Oghenebrume50 commented on index.html
> +      <div class="verse">
The content of this container are actually links and images, please check this out on the original site for comparison and implement according

2019-08-29 16:19 UTC, Sick-Carlito commented
The size is just fine on my size. I didn't manage to find what the problem was on your side. Thank you.
![Screenshot from 2019-08-29 18-37-33](https://user-images.githubusercontent.com/20436727/63957844-dc80ad80-ca91-11e9-970f-5a30789aa097.png)

2019-08-29 16:30 UTC, bolah2009 requested changes
# Good Job @Sick-Carlito 

## The [clone](https://raw.githack.com/Sick-Carlito/Apple-Page/9b5bb21b0ba046b897b89d6ab4c7969e34e39f3a/index.html) looks okay to me... :ok: 

@Oghenebrume50 might be using a different percentage zoom in the browser. :thinking: 

There's still one comment raised by @Oghenebrume50 you haven't fixed, kindly **use semantic HTML elements**.
     > Remember to use [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp).

Fix this and submit for another code review request. :blush: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-29 18:28 UTC, samgaco commented
### Everything looks correct :+1: The project is approved, congratulations on finishing your first solo project! :1st_place_medal: :clap: 

### You can go ahead and merge to the master branch and submit the project completion form. :100:

2019-08-29 18:45 UTC, merged

2019-08-29 18:46 UTC, Sick-Carlito commented
Thanks Guys!!